[package]
name = "rust_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
toml = "0.8.14"
serde = { version = "1.0.203", features = ["derive"] }
log = "0.4.22"
mockall = "0.13.0"
